version: '3'

volumes:
  go-app-skeleton-dev-postgres-data: {}

services:

  go-app-skeleton-dev-postgres:
    image: postgres:16
    networks:
      - go-app-skeleton-dev-network
    container_name: go-app-skeleton-dev-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - go-app-skeleton-dev-postgres-data:/var/lib/postgresql/data
    ports: #host_port : docker_port
      - "5432:5432"

  jaeger-all-in-one:
    image: jaegertracing/all-in-one
    networks:
      - go-app-skeleton-dev-network
    container_name: jaeger-all-in-one
    ports: #host_port : docker_port
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"

networks:
  go-app-skeleton-dev-network: {}
